/**
 * The pipeline's public run contract: what a caller passes to `generateMystery`, what it gets back, and the
 * progress / artifact callbacks.
 *
 * Moved verbatim from `mystery-orchestrator.ts` (code review ORC-06), which re-exports it, so the API and
 * every existing importer keep their paths. Its own module so `agents/context.ts` can name
 * `MysteryGenerationInputs` without importing the orchestrator — that type import closed an 18-file cycle.
 */
import type { CaseData } from "@cml/cml";
import type {
  ClueDistributionResult,
  FairPlayAuditResult,
  NarrativeOutline,
  CharacterProfilesResult,
  LocationProfilesResult,
  TemporalContextResult,
  BackgroundContextArtifact,
  HardLogicDeviceResult,
  ProseGenerationResult,
  NoveltyAuditResult,
  SettingRefinementResult,
  CastDesignResult,
  WorldDocumentResult,
} from "@cml/prompts-llm";
import type { GenerationReport, ValidationReport } from "@cml/story-validation";
import type { PrimaryAxisInput } from "./agents/premise.js";
import type { ResumeBundle } from "./resume-hydration.js";

// ============================================================================
// Public types
// ============================================================================

export interface MysteryGenerationInputs {
  /** e.g. "locked room murder in a manor" */
  theme: string;
  /**
   * A world for the story to draw on — "a racing stable", "a by-election" — that colours the setting,
   * the cast's occupations and the motive without being the mechanism. Generated by
   * scripts/run-params.mjs (STORY_ANGLES). Agents 2e/3b/3 see it inside the theme text; this field
   * exists because Agents 1 and 2 never see the theme at all.
   */
  storyAngle?: string;
  eraPreference?: string;
  locationPreset?: string;
  tone?: string;
  /** One of the five canonical axes; retired spellings are accepted. See CML_PRIMARY_AXES. */
  primaryAxis?: PrimaryAxisInput;

  /** suspects + witnesses; detective is always +1 */
  castSize?: number;
  castNames?: string[];
  /**
   * Optional gender lock map: character name → 'male' | 'female'.
   * When provided alongside castNames, Agent 2 is instructed to treat these as
   * non-negotiable. Prevents per-run gender ambiguity for names the LLM might
   * misread (e.g. gender-neutral titles or uncommon first names).
   */
  castGenders?: Record<string, 'male' | 'female'>;
  detectiveType?: "police" | "private" | "amateur";
  targetLength?: "short" | "medium" | "long";
  narrativeStyle?: "classic" | "modern" | "atmospheric";
  /**
   * A_92 — how much wit this book carries: "none" | "dry" | "classic" | "sharp".
   * Free text like tone, and anything unrecognised resolves to "classic", which is the behaviour
   * every run had before this existed. The band decides which humour styles Agent 2b may assign
   * and in which chapters Agent 9 asks for a wit beat; `wit-density.ts` then measures what arrived.
   */
  humourLevel?: string;

  /** Skip Agent 8 novelty check if true */
  skipNoveltyCheck?: boolean;
  /** Agent 8 similarity threshold, default 0.9 */
  similarityThreshold?: number;

  /** Chapters per LLM call (1–10, default 1) */
  proseBatchSize?: number;

  /** Optional filesystem path for Agent 9 checkpoint persistence/resume JSON. */
  agent9CheckpointPath?: string;
  /** When true, Agent 9 resumes from the checkpoint file if available. */
  resumeAgent9FromCheckpoint?: boolean;

  runId?: string;
  projectId?: string;

  /** Pillar 1: accumulate locked facts from Agent 3b and propagate to Agents 5, 7, 9 */
  enableLockedFactRegistry?: boolean;
  /** Pillar 1: pre-generation gate — halt if outline/clues disagree with registry */
  enableLockedFactGate?: boolean;
  /** Pillar 2: assemble Character Context Bundle from Agents 2b + 65 and pass to Agent 9 */
  enableCharacterBundle?: boolean;
  /** Pillar 3: halt pipeline when a quality-evaluator result has blocking=true */
  enableBindingGates?: boolean;
  /** Pillar 3: override a blocking gate — log audit warning instead of throwing */
  forceWarnings?: boolean;

  /**
   * R5 — resume a previously-failed run instead of restarting it.
   *
   * `resumeFromRunId` identifies the run for reporting; `resumeArtifacts` carries that run's
   * persisted artifacts, keyed by the same names `onArtifact` writes. Any stage whose artifact is
   * present is SKIPPED; the pipeline starts at the first missing one.
   *
   * The caller owns loading (the API holds the artifact store); the orchestrator owns skipping.
   * That split keeps this module free of storage concerns and makes the behaviour unit-testable.
   */
  resumeFromRunId?: string;
  resumeArtifacts?: ResumeBundle;
  /** Pillar 6: inject BANNED PARAGRAPH blocks and structural-pivot mode into Agent 9 retry prompts
    *  when a paragraph fingerprint failure recurs across attempts. Default is enabled;
    *  set false only for explicit control experiments. */
  enableSurgicalFingerprintRetry?: boolean;
  /** Pillar 4: require pivotElement, factEstablished, permittedBehavioursByAct, and
   *  redHerringPlacement per outline scene; post-Agent-7 validator halts on null/generic values;
   *  Agent 9 enacts pivotElement, factEstablished, and redHerringPlacement per chapter */
  enableOutlineCompleteness?: boolean;
}

export interface MysteryGenerationProgress {
  stage:
    | "setting"
    | "cast"
    | "background-context"
    | "hard_logic_devices"
    | "cml"
    | "clues"
    | "fairplay"
    | "narrative"
    | "profiles"
    | "location-profiles"
    | "temporal-context"
    | "world-builder"
    | "prose"
    | "editing"
    | "scoring"
    | "validation"
    | "novelty"
    | "novelty_math"
    | "complete";
  message: string;
  percentage: number;
  timestamp: Date;
}

export interface MysteryGenerationResult {
  // Final outputs
  cml: CaseData;
  clues: ClueDistributionResult;
  fairPlayAudit: FairPlayAuditResult;
  narrative: NarrativeOutline;
  characterProfiles: CharacterProfilesResult;
  locationProfiles: LocationProfilesResult;
  temporalContext: TemporalContextResult;
  worldDocument?: WorldDocumentResult;
  backgroundContext: BackgroundContextArtifact;
  hardLogicDevices: HardLogicDeviceResult;
  prose: ProseGenerationResult;
  noveltyAudit?: NoveltyAuditResult;
  validationReport: ValidationReport;
  scoringReport?: GenerationReport;

  // Intermediate results
  setting: SettingRefinementResult;
  cast: CastDesignResult;

  metadata: {
    runId: string;
    projectId?: string;
    totalCost: number;
    totalDurationMs: number;
    agentCosts: Record<string, number>;
    agentDurations: Record<string, number>;
    revisedByAgent4: boolean;
    revisionAttempts?: number;
    revisedByAgent4FairPlay: boolean;
    fairPlayRevisionAttempts: number;
  };

  status: "success" | "warning" | "failure";
  warnings: string[];
  errors: string[];
}

export type ProgressCallback = (progress: MysteryGenerationProgress) => void;

/**
 * Called immediately after each pipeline agent completes with a persisted-ready
 * artifact. Allows the API to write incremental artifacts to the DB during the
 * run so the UI can display them via polling before the pipeline finishes.
 */
export type ArtifactCallback = (type: string, payload: unknown) => Promise<void>;
