/**
 * PROSE ENGINE v2 — THE SELECTOR (ANALYSIS_99 §10.6).
 *
 * ── WHY SELECTION IS THE MOVE THAT ATTACKS CONSISTENCY ───────────────────────────────────────────
 *
 * The owner's bar is 90 CONSISTENTLY, and a floor is a property of the WORST draft, not the mean.
 * Over August and September the headline ran mean 81.2, sd 3.6, floor 74 — and every book was the
 * model's first answer. WP-001 §8: post-training collapses an aligned model toward a few
 * stereotypical completions, and the one stage in this pipeline that generates several candidates
 * and picks (premise, five divergent candidates) is the one category with thirteen 9s. Verbalized
 * sampling recovers 1.6-2.1x diversity at inference time with no retraining.
 *
 * Drafting k times and keeping one cuts the lower tail without touching the mean. That is the whole
 * claim, and it is worth what it costs only if the thing doing the keeping agrees with the reader.
 *
 * ── SO THE SELECTOR WAS MEASURED BEFORE IT WAS BUILT ─────────────────────────────────────────────
 *
 * `scripts/selector-calibrate.mjs`, over all 49 manuscripts on disk with an external read and at
 * least 8,000 words (CLAUDE.md's floor: eight truncated May/June books manufacture relationships
 * with anything length-related):
 *
 *   instrument              rho vs the reader's headline
 *   register rate                 -0.502      the only previously validated predictor
 *   dialogue-open share           +0.337
 *   long-sentence share           +0.293
 *   wit per 10k                   +0.250
 *   em-dash per 1k                +0.222
 *   repetition per 10k            -0.152
 *
 *   register alone                 0.502
 *   THE COMPOSITE                  0.571
 *
 * **The composite beats the best single instrument by 0.07, and clears the bar the design wrote down
 * (|rho| >= 0.55).**
 *
 * ── AND THE FIRST RUN OF THIS SCRIPT DID NOT, FOR A REASON WORTH KEEPING ─────────────────────────
 *
 * It reported register at -0.454 and the composite at 0.524, and the bar was recorded as missed. The
 * cause was not the instruments: `story_20260912-1815/chatgpt-review.txt` holds THREE reads of TWO
 * books — 79 and 82 of a ballet-intermission book filed there by mistake, then 87, an as-written read
 * of the Lockwood book the folder actually holds — and both this script and
 * `external-read-ledger.mjs` took the FIRST, pairing the Lockwood manuscript with another book's
 * score. (The first version of this comment said "three reads of one book, 87 after repairs"; A_101
 * §10 corrected it.) Fixed at the ledger (W1) and imported here rather than re-implemented.
 *
 * AND A_101 §4, 2026-09-23: refitted on 55 v1 reads, register predicts v2's books at 88-90 and they
 * read 80-84. v2's register (0.012-0.034) is below every v1 book's (min 0.058), so these weights are
 * being used outside the range they were fitted on.
 *
 * ── AND THE WEIGHTS ARE THE ONES WRITTEN DOWN FIRST ──────────────────────────────────────────────
 *
 * The calibration script prints five candidate weightings: register only (0.502), register plus the
 * two page instruments (0.556), equal weight by sign (0.583), weight-by-measured-rho (0.574), and
 * the proposed weighting (0.571). They span 0.027, which says the signal is in USING SEVERAL
 * INSTRUMENTS and not in the tuning — so the shipped weighting is the one this file proposed before
 * the table existed. Picking the top row after seeing it would be fitting on the data that judges it,
 * with n=49 and six parameters.
 *
 * ── HARD GATES ARE NOT INSTRUMENTS ───────────────────────────────────────────────────────────────
 *
 * Contract fidelity — a clue missing, the culprit named early, a clue id in the prose — is not a
 * quality score to be traded against register. A draft with hard failures ranks below every draft
 * without, and is NEVER discarded: L4, the run always has a book. If every draft fails, the one with
 * the fewest proceeds and each failure becomes a finding for the editor.
 */

import {
  machineRegisterRate,
  repetitionDensity,
  witDensity,
  REGISTER_TELEMETRY_THRESHOLD,
} from "@cml/prose-guard";
import { chapterMentionsRequiredClue, tokenMatchesText } from "@cml/prompts-llm";
import { indexChapters } from "./chapter-index.js";
import { namesAsCulprit } from "./culprit.js";

import type {
  ContractCore,
  Draft,
  DraftScore,
  HardGateHit,
  InstrumentVector,
  ProseChapterLike,
  SceneContract,
} from "./types.js";

/**
 * Corpus statistics, generated by `scripts/selector-calibrate.mjs` on 2026-09-18 over 49 read
 * manuscripts. Regenerate with `--emit` after a batch of reads; the weights are editorial and are
 * argued in the header, the means and standard deviations are not.
 */
export const CALIBRATION_N = 49;
export const CALIBRATION = {
  registerRate: { mean: 0.1204, sd: 0.0334, weight: -3 },
  repetitionPer10k: { mean: 53.6857, sd: 94.3212, weight: -1 },
  dialogueOpenShare: { mean: 0.1337, sd: 0.0513, weight: 1.5 },
  longSentenceShare: { mean: 0.0402, sd: 0.0135, weight: 1 },
  emDashPer1k: { mean: 0.3568, sd: 0.482, weight: 0.5 },
  witPer10k: { mean: 8.7245, sd: 6.9637, weight: 1 },
} as const;

/** The composite's measured agreement with the reader, and the number it has to beat. */
export const CALIBRATION_RHO = { composite: 0.571, registerAlone: 0.502, designBar: 0.55 } as const;

/**
 * The lowest machine-register of any v1 book with an external read (A_101 §4).
 *
 * Below it the calibration has no evidence at all. v2's read books sit at 0.012–0.034; refitted on 55
 * v1 reads, register predicts them at 88–90, and they read 80–84. So register enters the composite no
 * lower than this floor: between two drafts that are both under it, register decides nothing and the
 * other instruments do. The vector still reports the true rate.
 *
 * Units: the calibration measured saved manuscripts and the selector measures draft paragraphs,
 * which read up to ±0.015 apart on the same book. It is a floor, not a threshold, so the placement
 * need not be exact to stop the selector preferring ever-lower register past where it predicts.
 */
export const REGISTER_FLOOR = 0.058;

type CalibratedKey = keyof typeof CALIBRATION;

const textOf = (chapters: ReadonlyArray<ProseChapterLike>): string =>
  chapters.map((c) => (c.paragraphs ?? []).join("\n\n")).join("\n\n");

const paragraphsOf = (chapters: ReadonlyArray<ProseChapterLike>): string[] =>
  chapters.flatMap((c) => c.paragraphs ?? []);

const sentencesOf = (text: string): string[] => text.split(/(?<=[.!?])\s+/).filter((s) => s.trim());

/** Opens on speech. The canon opens three paragraphs in five this way; our books open one in eight. */
const opensOnSpeech = (paragraph: string): boolean => /^["“‘']/.test(paragraph.trim());

/**
 * An em-dash, however the pipeline spelled it. The saved manuscript is ASCII-normalised, so the
 * character survives as a spaced hyphen — counting only the character read 0.000 on all 49 books,
 * which is a claim about the instrument.
 */
const EM_DASH_RE = /—|\s-{1,2}\s/g;

export const measureInstruments = (
  chapters: ReadonlyArray<ProseChapterLike>,
  witTargetPer10k = 41,
): InstrumentVector => {
  const body = textOf(chapters);
  const paragraphs = paragraphsOf(chapters);
  const words = body.split(/\s+/).filter(Boolean).length || 1;
  const sentences = sentencesOf(body);
  const long = sentences.filter((s) => s.split(/\s+/).filter(Boolean).length > 30).length;
  const wit = witDensity(body);
  return {
    registerRate: machineRegisterRate(body, REGISTER_TELEMETRY_THRESHOLD).rate,
    repetitionPer10k: repetitionDensity(body).per10k,
    copiedSpans: 0,
    dialogueOpenShare: paragraphs.length > 0 ? paragraphs.filter(opensOnSpeech).length / paragraphs.length : 0,
    longSentenceShare: sentences.length > 0 ? long / sentences.length : 0,
    witPer10k: wit.per10k,
    witTarget: witTargetPer10k,
    turnChapters: 0,
    turnWindow: 0,
    clocksOffTable: 0,
    pronounMismatches: 0,
    words,
  };
};

/** The em-dash rate, kept out of `InstrumentVector` because only the selector reads it. */
export const emDashPer1k = (chapters: ReadonlyArray<ProseChapterLike>): number => {
  const body = textOf(chapters);
  const words = body.split(/\s+/).filter(Boolean).length || 1;
  return (1_000 * (body.match(EM_DASH_RE) ?? []).length) / words;
};

// ── hard gates ───────────────────────────────────────────────────────────────────────────────────

/**
 * A scaffold token: an internal word that has no business on a page.
 *
 * TWO regexes, because the tokens fall into two kinds and one flag cannot serve both.
 *
 * `JARGON_RE` is case-insensitive: these are identifiers and phrases from our own artifacts that no
 * Golden Age novelist writes — `clue_compass_tilt`, `prose_requirements`, "the discriminating test".
 * Lowercased in prose they are still ours, so folding case is right.
 *
 * `MARKER_RE` is case-SENSITIVE, and that is the whole point. `CASE` and `CML` are the CML markers,
 * and under `/i` they become the ordinary words *case* and *cml* — in a DETECTIVE NOVEL. MEASURED
 * 2026-09-19 on `resume-1789805865810`: chapter 5's *"She retrieved her cigarette case"* was
 * reported as generator scaffolding. Only one fired per chapter because `exec` takes the first
 * match, which hid how often it was wrong. This is `domain-nouns-collide-with-validator-wordlists`
 * on the most predictable noun in the genre, and the fix is the flag, not a list of exceptions.
 */
const JARGON_RE =
  /\b(clue_[a-z0-9_]+|act_?\d+|scene_?\d+|sceneNumber|prose_requirements|hidden_model|discriminating[_ ]test|locked[_ ]fact)\b/i;
const MARKER_RE = /\b(CASE|CML)\b/;

/** The first scaffold token in a body, of either kind, or null. */
const findScaffold = (body: string): string | null =>
  JARGON_RE.exec(body)?.[0] ?? MARKER_RE.exec(body)?.[0] ?? null;

export const checkHardGates = (
  chapters: ReadonlyArray<ProseChapterLike>,
  core: ContractCore,
  expected: ReadonlyArray<number>,
  clueDistribution?: { clues?: unknown[] },
): HardGateHit[] => {
  const hits: HardGateHit[] = [];
  const byChapter = indexChapters(chapters, expected);

  for (const chapter of expected) {
    if (!byChapter.has(chapter)) hits.push({ kind: "chapter_missing", chapter, detail: "not in the draft" });
  }

  const castNames = core.scenes.flatMap((s) => s.present);

  for (const [chapter, written] of byChapter) {
    const scene: SceneContract | undefined = core.scenes.find((s) => s.chapter === chapter);
    if (!scene) continue;
    const body = (written.paragraphs ?? []).join("\n");

    for (const surface of scene.mustSurface) {
      const present = clueDistribution
        ? chapterMentionsRequiredClue(body, surface.id, clueDistribution as never, castNames)
        : surface.keyTerms.length > 0 &&
          surface.keyTerms.filter((t) => tokenMatchesText(t, body.toLowerCase())).length >=
            Math.max(2, Math.ceil(surface.keyTerms.length * 0.5));
      if (!present) {
        hits.push({ kind: "clue_missing", chapter, detail: `${surface.id}: ${surface.keyTerms.slice(0, 4).join(", ")}` });
      }
    }

    for (const withheld of scene.mustNotReveal) {
      if (withheld.what === "culprit") {
        for (const culprit of core.fairPlay.culprits) {
          if (namesAsCulprit(body, culprit)) {
            hits.push({ kind: "culprit_early", chapter, detail: `${culprit} named as the murderer, owed to chapter ${withheld.until}` });
          }
        }
        continue;
      }
      if (withheld.what === "mechanism") continue; // told-not-shown is a CRITIC finding, not a gate
      const owed = core.scenes
        .flatMap((s) => s.mustSurface)
        .find((s) => s.id === withheld.what);
      /**
       * ── THE THRESHOLD IS FROM THE CORPUS, NOT A GUESS ─────────────────────────────────────────
       *
       * At ">= max(3, 70%) of the key terms" this fired 9-19 times on EVERY draft of two books
       * (2026-09-22, six saved drafts). The terms it matched were *manor, hall, clock, half, past,
       * seven* — the book's setting, recurring in chapter 1 because the book is about that clock in
       * that hall, not because a clue was staged there. Swept over the same six drafts:
       *
       *     >= max(3, 70%)   19 / 17 / 17   and   13 / 9 / 12
       *     >= max(4, 80%)    5 /  3 /  6   and    7 / 2 /  3
       *     >= max(4, 90%)    2 /  1 /  0   and    1 / 0 /  1
       *
       * A clue genuinely staged in the wrong chapter is rare; the last row looks like that.
       */
      if (!owed || owed.keyTerms.length < 4) continue;
      const lowered = body.toLowerCase();
      const hitTerms = owed.keyTerms.filter((t) => tokenMatchesText(t, lowered)).length;
      if (hitTerms >= Math.max(4, Math.ceil(owed.keyTerms.length * 0.9))) {
        hits.push({ kind: "clue_early", chapter, detail: `${withheld.what} is owed to chapter ${withheld.until}` });
      }
    }

    const scaffold = findScaffold(body);
    if (scaffold) hits.push({ kind: "scaffold", chapter, detail: scaffold });
  }

  /**
   * THE CONDITION THAT STOPS THE RUN MUST BE ONE THE SELECTOR CAN SEE.
   *
   * `applyGate` stops a book whose reveal never attributes the act. This function — which is what
   * ranks drafts and what feeds the editor — did not check it, so two things followed: the selector
   * could not prefer a draft that shipped, and no editor was ever asked to repair the one defect
   * that loses the whole run.
   *
   * MEASURED, `resume-1789846757984`: three drafts of one contract, draft 3 named the culprit and
   * drafts 1 and 2 did not. The selector chose draft 2 on composite. The run stopped.
   */
  /**
   * ONE hit, at book level, when the draft is under the contract's minimum.
   *
   * The composite has no length term — recorded in §22.5 as a reason it was never wrong — and on
   * the first best-of-three run it chose the SHORTEST of three drafts (6,485 of 7,225 / 6,485 /
   * 6,783) against a minimum of 7,500. One hit rather than one per short chapter, so a draft that
   * meets the floor beats any that does not, and among drafts that all miss it the composite still
   * decides; ten hits would let a chapter's length outrank every instrument that predicts the score.
   * It reaches no editor (`collectCheckerFindings` skips it): an editor cannot lengthen a book.
   */
  const bookWords = [...byChapter.values()].reduce(
    (n, c) => n + (c.paragraphs ?? []).join(" ").split(/\s+/).filter(Boolean).length,
    0,
  );
  if (byChapter.size === expected.length && bookWords < core.book.words.min) {
    hits.push({ kind: "book_short", chapter: 0, detail: `${bookWords} words against a minimum of ${core.book.words.min}` });
  }

  const culprits = core.fairPlay.culprits;
  if (culprits.length > 0) {
    const atOrAfterReveal = [...expected]
      .sort((a, b) => a - b)
      .filter((c) => c >= core.roles.reveal)
      .map((c) => (byChapter.get(c)?.paragraphs ?? []).join(" "))
      .join(" ");
    if (atOrAfterReveal.trim() && !culprits.some((c) => namesAsCulprit(atOrAfterReveal, c))) {
      hits.push({
        kind: "reveal_unnamed",
        chapter: core.roles.reveal,
        detail: `${culprits.join(", ")} is never named as the murderer at or after chapter ${core.roles.reveal}`,
      });
    }
  }

  return hits;
};

// ── the composite ────────────────────────────────────────────────────────────────────────────────

/**
 * Score a draft. `hard` ranks above everything; `composite` orders drafts that are equally clean.
 *
 * WIT IS SCORED RAW, NOT AGAINST THE BAND, and the first cut had that wrong. It scored closeness to
 * the band's target and then normalised that against the corpus statistics for the RAW rate — two
 * different quantities through one z-score, which is how a term ends up meaning nothing (on the
 * first fixture it produced an identical contribution for a target of 0 and a target of 60).
 *
 * The calibration measured the raw rate against the reader's headline (+0.187), so the raw rate is
 * what the composite carries. The band is the OWNER's ask, not the reader's, and it is reported in
 * the vector (`witPer10k` against `witTarget`) for the run report and the brief to answer. A
 * band-conformance term would need its own measurement against reads of books written to a band,
 * and this project has one such read.
 */
export const scoreDraft = (
  draft: Draft,
  core: ContractCore,
  expected: ReadonlyArray<number>,
  options: { witTargetPer10k?: number; clueDistribution?: { clues?: unknown[] } } = {},
): DraftScore => {
  const witTarget = options.witTargetPer10k ?? 41;
  const vector = measureInstruments(draft.chapters, witTarget);
  const values: Record<CalibratedKey, number> = {
    registerRate: Math.max(vector.registerRate, REGISTER_FLOOR),
    repetitionPer10k: vector.repetitionPer10k,
    dialogueOpenShare: vector.dialogueOpenShare,
    longSentenceShare: vector.longSentenceShare,
    emDashPer1k: emDashPer1k(draft.chapters),
    witPer10k: vector.witPer10k,
  };
  const contributions: Record<string, number> = {};
  let composite = 0;
  for (const key of Object.keys(CALIBRATION) as CalibratedKey[]) {
    const { mean, sd, weight } = CALIBRATION[key];
    const z = (values[key] - mean) / (sd || 1);
    const contribution = weight * z;
    contributions[key] = Number(contribution.toFixed(4));
    composite += contribution;
  }
  return {
    hard: checkHardGates(draft.chapters, core, expected, options.clueDistribution),
    vector,
    composite: Number(composite.toFixed(4)),
    contributions,
  };
};

export interface ScoredDraft {
  draft: Draft;
  score: DraftScore;
}

/**
 * Choose between drafts: fewest hard failures first, then the highest composite. Never returns
 * nothing when given something (L4) — a draft with no chapters loses to one with any, and if every
 * draft is empty the caller gets `null` and owns that, because there is no book to ship.
 */
/**
 * The hard-gate kinds that RANK drafts: the ones that stop a run or spoil the book for a reader.
 *
 * Every kind used to count one, so any hit outranked the whole composite. MEASURED 2026-09-22,
 * `resume-1790097751711`: draft 1 was 7,615 words, above the floor, composite 22.92, and named the
 * culprit; the selector chose draft 2 — 6,620 words, BELOW the floor, composite 20.07 — because
 * draft 1 carried 13 `clue_early` hits to draft 2's 9 plus one `book_short`. Thirteen vocabulary
 * overlaps outranked a sub-floor book with a worse composite, and the shipped manuscript was the
 * shortest of the three on offer.
 *
 * `clue_early` is an ownership mismatch — a clue's terms appearing before the chapter the contract
 * gave it — which is a finding for the editor and not a reason to prefer one draft over another.
 * The kinds below are.
 */
export const RANKING_KINDS: ReadonlySet<HardGateHit["kind"]> = new Set([
  "chapter_missing",
  "reveal_unnamed",
  "culprit_early",
  "book_short",
  "scaffold",
  "clue_missing",
]);

/** How many of a draft's hard hits are the kind that ranks it. */
export const rankingFailures = (score: DraftScore): number =>
  score.hard.filter((h) => RANKING_KINDS.has(h.kind)).length;

export const chooseDraft = (scored: ReadonlyArray<ScoredDraft>): ScoredDraft | null => {
  const real = scored.filter((s) => s.draft.chapters.length > 0);
  if (real.length === 0) return null;
  return [...real].sort((a, b) => {
    const ra = rankingFailures(a.score);
    const rb = rankingFailures(b.score);
    if (ra !== rb) return ra - rb;
    return b.score.composite - a.score.composite;
  })[0]!;
};

/** One line per draft for the run report, so a choice can be read back without re-running it. */
export const summariseSelection = (scored: ReadonlyArray<ScoredDraft>, chosen: ScoredDraft | null): string => {
  const rows = scored.map((s) => {
    const mark = s === chosen ? "*" : " ";
    const v = s.score.vector;
    return (
      `${mark} draft ${s.draft.attempt}: composite ${s.score.composite.toFixed(2)}, ` +
      `hard ${rankingFailures(s.score)} ranking of ${s.score.hard.length}, register ${v.registerRate.toFixed(3)}, ` +
      `repetition ${v.repetitionPer10k.toFixed(1)}, speech-open ${(100 * v.dialogueOpenShare).toFixed(0)}%, ` +
      `tail ${(100 * v.longSentenceShare).toFixed(0)}%, wit ${v.witPer10k.toFixed(1)}/${v.witTarget}`
    );
  });
  return rows.join("\n");
};
