import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
for (const k of ["CML_VERIFIED_FIXES","CML_PROMPT_TRIMS"]) process.env[k] = "1";
const run = await import(pathToFileURL("C:/CML/apps/worker/dist/jobs/agents/agent9-v2/run.js").href);
const pe = await import(pathToFileURL("C:/CML/packages/prose-engine/dist/index.js").href);
const hyd = await import(pathToFileURL("C:/CML/apps/worker/dist/jobs/resume-hydration.js").href);
const store = await import(pathToFileURL("C:/CML/apps/worker/dist/jobs/artifact-store.js").href);
const pid = process.argv[2], lockedFile = process.argv[3];
const st = store.loadArtifactStore("C:/CML");
const { bundle } = hyd.loadResumeBundle(st, pid, "prose");
const spec = store.specToInputs(store.resolveProjectSpec("C:/CML", pid).spec ?? {});
const ctx = { inputs: spec, primaryAxis: spec.primaryAxis, warnings: [] };
hyd.applyResumeBundle(ctx, bundle);
console.log("restored ctx fields:", Object.keys(ctx).join(","), "| lockedFactRegistry on ctx after resume hydration:", ctx.lockedFactRegistry);
const chronoBlock = (t) => { const i = t.indexOf("Every one of these is written the same way"); return i < 0 ? "" : t.slice(i, t.indexOf("\n\n", i)); };
const asResumed = pe.buildBookContract(run.buildContractInput(ctx));
const reg = JSON.parse(readFileSync(lockedFile, "utf8")).registry;
const asFresh = pe.buildBookContract(run.buildContractInput({ ...ctx, lockedFactRegistry: reg }));
const a = chronoBlock(asResumed.bible.text), b = chronoBlock(asFresh.bible.text);
console.log("chronology lines — as resumed:", a.split("\n").length - 1, " with the run's registry:", b.split("\n").length - 1);
console.log("lines only the fresh-run bible carries:\n" + b.split("\n").filter(l => !a.includes(l)).join("\n"));
