/**
 * GENERATED by `node scripts/build-voice-corpus.mjs --write` — do not edit by hand.
 *
 * A_75 §6.1 (P1) — what the last 20 manuscripts actually sound like, so the VoiceSpec
 * generator can be told to diverge from real books rather than from a generic instruction to be
 * original. That specificity is why the `premise` engine works and nothing else does (A_72 §2.1).
 *
 * MEASURED at generation time: corpus mean 15.61 words per sentence, full spread
 * 3.56 words across 20 books. For scale, the WITHIN-book standard
 * deviation runs about 8 words — so the entire between-book spread of this corpus is a fraction of
 * the variation inside any single one of them. That is A_75 §3's finding as a number, and it is the
 * thing a new spec has to break.
 *
 * Re-run after a batch of new runs; a stale corpus asks the generator to diverge from books it is no
 * longer competing with.
 */

export interface VoiceCorpusEntry {
  story: string;
  title: string;
  /** Words per sentence, measured over the shipped manuscript. */
  mean: number;
  /** Within-book standard deviation of sentence length. */
  sd: number;
}

export const VOICE_CORPUS: ReadonlyArray<VoiceCorpusEntry> = [
  { story: "story_20260807-1412", title: "The Clock's Silent Deception", mean: 16.40, sd: 8.54 },
  { story: "story_20260814-2033", title: "The Frozen Hour at Coastview Hotel", mean: 14.33, sd: 7.57 },
  { story: "story_20260815-2027", title: "The Pendulum's Secret", mean: 16.45, sd: 7.86 },
  { story: "story_20260817-2209", title: "The Reversed Pendulum at Seacliff Hotel", mean: 15.43, sd: 8.45 },
  { story: "story_20260819-0147", title: "The Sailed Backwards Hour at Cliffhaven Hotel", mean: 16.25, sd: 8.10 },
  { story: "story_20260819-2047", title: "The Delayed Strike at Cliffhaven Hotel", mean: 15.19, sd: 8.17 },
  { story: "story_20260819-2302", title: "The Fete's Frozen Hour", mean: 17.18, sd: 8.18 },
  { story: "story_20260821-2017", title: "The Clockwork Alibi at Seabreeze Hotel", mean: 14.71, sd: 7.95 },
  { story: "story_20260821-2120", title: "The Authority's Shadow on the Promenade", mean: 16.36, sd: 8.63 },
  { story: "story_20260822-1028", title: "The Tidal Hour at Seabreeze Hotel", mean: 16.52, sd: 8.60 },
  { story: "story_20260822-1047", title: "The Shadowed Staircase Secret", mean: 14.81, sd: 8.28 },
  { story: "story_20260822-1109", title: "The Reflection Game at Seabreeze Hotel", mean: 16.62, sd: 8.07 },
  { story: "story_20260822-1124", title: "The Anchored Hour at Seaview Hotel", mean: 16.09, sd: 8.40 },
  { story: "story_20260822-1140", title: "The Authority's Tide at Seabreeze Hotel", mean: 16.48, sd: 8.58 },
  { story: "story_20260823-1715", title: "The Rising Tide at Cliffhaven", mean: 16.28, sd: 7.66 },
  { story: "story_20260823-2038", title: "The Hourglass Deception at Cliffside Bluffs", mean: 15.30, sd: 7.51 },
  { story: "story_20260825-1838", title: "The Case of the Rewound Lobby Clock", mean: 14.35, sd: 7.85 },
  { story: "story_20260825-2102", title: "The Thirty-Minute Error: A Seaside Hotel Clockwork Murder", mean: 13.62, sd: 7.76 },
  { story: "story_20260826-1708", title: "The Elevator Cage Enigma", mean: 15.09, sd: 7.95 },
  { story: "story_20260826-1753", title: "The Canary's Slippers: A Seaside Hotel Identity Mystery", mean: 14.79, sd: 7.73 },
];

/** Arithmetic mean of the corpus means — the centre a new spec should NOT sit on. */
export const VOICE_CORPUS_MEAN = 15.61;
/** Widest gap between any two books in the corpus, in words per sentence. */
export const VOICE_CORPUS_SPREAD = 3.56;
export const VOICE_CORPUS_MANUSCRIPTS = 20;
